spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/umcstudy"
    username: root
    password: Mchwoo9209@
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      show-sql : true
      hibernate:
        ddl-auto : none
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000